CREATE TABLE Supplier (
  SID INT PRIMARY KEY,
  Sname VARCHAR(100),
  Branch VARCHAR(50),
  City VARCHAR(50),
  Phone INTEGER(10) NOT NULL
);
DESC Supplier;

ALTER TABLE Supplier ADD COLUMN State VARCHAR(20);
ALTER TABLE Supplier DROP COLUMN City;
ALTER TABLE Supplier MODIFY COLUMN Phone VARCHAR(20);
ALTER TABLE Supplier RENAME COLUMN State TO STATE_RE;

RENAME TABLE Supplier TO SUPP;
DESC SUPP;

TRUNCATE TABLE SUPP;
DESC SUPP;
