CREATE TABLE Supplier(
  -- PRIMARY KEY
  SID INT PRIMARY KEY, 
  Sname VARCHAR(20),
  Branch VARCHAR(20),
  City VARCHAR(20),      
  Phone INTEGER NOT NULL 
  );
  DESC Supplier;
 
CREATE TABLE Part(
  PID INT PRIMARY KEY,
  Pname VARCHAR(20) NOT NULL UNIQUE,
  Color VARCHAR(30),
  Price DECIMAL(10,2)
);

CREATE TABLE SUPPLIES(
  SID INT NOT NULL,
  PID INT NOT NULL,
  qty INT NOT NULL,
  DATE_SUPP DATE NOT NULL,
  PRIMARY KEY(SID,PID,qty,DATE_SUPP),
  FOREIGN KEY (SID) REFERENCES Supplier(SID)
);

CREATE TABLE Supplier (
    SID INT PRIMARY KEY,
    Sname VARCHAR(50) NOT NULL,
    branch VARCHAR(10) NOT NULL,
    city VARCHAR(30),
    phone VARCHAR(10),
    CHECK (branch IN ('NORTH','SOUTH','EAST','WEST')),
    CHECK (phone IS NULL OR phone REGEXP '^[0-9]{10}$')
);

DESC Part;
DESC SUPPLIES;



