CREATE TABLE SUPPLLIER(
  SID INT PRIMARY KEY,
  NAME VARCHAR(10) NOT NULL,
  BRANCH VARCHAR(10),
  CITY VARCHAR(10),
  PHONE INTEGER(10) NOT NULL
);
CREATE TABLE PART(
  PID INT PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  COLOR VARCHAR(10),
  PRICE DECIMAL(10,2)
);
CREATE TABLE SUPPLIES(
  SID INT NOT NULL,
  PID INT NOT NULL,
  QTY INT NOT NULL,
  DATE_SUPP DATE NOT NULL,
  PRIMARY KEY(SID,PID,DATE_SUPP),
  FOREIGN KEY (SID) REFERENCES SUPPLLIER(SID),
  FOREIGN KEY (PID) REFERENCES PART(PID)
);

START TRANSACTION;
INSERT INTO SUPPLLIER VALUE (20400,'ROUSHAN','NORTH','DELHI',896951);
INSERT INTO SUPPLLIER VALUE (20401,'AKHTAR','EAST','KOLKATA',709831);
INSERT INTO PART VALUE (30100,'BOLT','SILVER',89);
INSERT INTO PART VALUE(30101,'KILL','RED',23);
SAVEPOINT SP1;

INSERT INTO SUPPLIES VALUE (20401,30101,3,'2025-01-12');
SAVEPOINT SP2;
SELECT * FROM SUPPLLIER;
SELECT * FROM SUPPLIES;
